# _config.yml

# Название сайта
title: "Life Chronicles"

# Базовый URL (обычно имя репозитория)
baseurl: "/"

# URL сайта
url: "https://yourusername.github.io/LifeChronicles"

# Выберите тему GitHub Pages
# 1. Minimal
# theme: jekyll-theme-minimal

# 2. Cayman
# theme: jekyll-theme-cayman

# 3. Slate
# theme: jekyll-theme-slate

# 4. Architect
theme: jekyll-theme-architect

# 5. Hacker
# theme: jekyll-theme-hacker

# 6. Modernist
# theme: jekyll-theme-modernist

# 7. Tactile
# theme: jekyll-theme-tactile

# Автор сайта
author: "Your Name"

# Описание сайта
description: "Chronicles of life events and moments"

# Ссылки на социальные сети (пример)
social_links:
  twitter: your_twitter_handle
  github: yourusername
  linkedin: your-linkedin-profile

# Markdown и синтаксическая подсветка
markdown: kramdown
highlighter: rouge

# Параметры для создания меню (необязательно)
# navigation:
#   - title: "Home"
#     url: "/"
#   - title: "About"
#     url: "/about"
#   - title: "Contact"
#     url: "/contact"
